import type { Metadata } from 'next'
import { Inter, Noto_Serif } from 'next/font/google'
import './globals.css'


const inter = Inter({ 
  subsets: ['latin'],
  weight: ['300','400','500','600','700'],
  variable: '--font-inter'
})

const notoSerif = Noto_Serif({ 
  subsets: ['latin'], 
  weight: ['300','400','500','600','700'],
  variable: '--font-noto-serif',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${notoSerif.variable}`}>{children}</body>
    </html>
  )
}
